# Python 101

## Basics

### Expression

In [1]:
1 + 4 * 3

13

In [2]:
(1 + 3) * 4 

16

### Variable

In [6]:
x = 5 # Variable vom Typ Integer(Ganze Zahl)
y = 3.14 # Variable vom Typ Float(Fließkommazahl)
print(x)
print(y)

5
3.14


## Datatypes

### Integer (Ganze Zahl)

In [12]:
print(123123123123123123123123123123123123123123123123 + 1)
print(10)

123123123123123123123123123123123123123123123124
10


Der zugrunde liegende Typ ist Integer, unabhängig von der Basis - zBsp.: Binär, Oktal, and Hexadezimal - die der Zahl zugrunde liegt:

In [1]:
type(10)

int

In [2]:
type(0o10)

int

In [3]:
type(0x10)

int

### Float (Fließkommazahl)

In [18]:
4.2

4.2

In [19]:
type(4.2)

float

In [20]:
4.

4.0

In [21]:
.2

0.2

In [23]:
.4e7

4000000.0

In [22]:
type(.4e7)

float

In [24]:
4.2e-4

0.00042

#### Challenge: Float
Konvertiere die Fließkommazahl 3.1456 in eine ganze Zahl.

#### Lösung:

In [47]:


























x = 3.1456
y = int(x)
print(y)
print(type(y))

3
<class 'int'>


### Strings (Zeichenketten)

In [1]:
print("Hello World")  

Hello World


In [2]:
type("Hello World")

str

In [3]:
'' # ein leerer String

''

In [4]:
print('Hello World (') !.') 

SyntaxError: invalid syntax (<ipython-input-4-c857d5cf62e8>, line 1)

### Challenge:Strings

Verwenden Sie nur die String-Addition (Verkettung) und die Funktion `str.join`, kombinieren Sie` declaration` und `sayings`:

```python
declaration = "\"Wen fliegen über Fliegen fliegen :\n"
sayings = ['"fliegen"'] * 3 + ['"nach\""']
# the (\') escapes the quote
```

zu einer Variablen, `sentence`, die, wenn gedruckt, dies tut:

```python
>>> print(sentence)
Wenn fliegen über Fliegen:
"fliegen", "fliegen", "fliegen", "nach"!
```

### Lösung: Strings

In [6]:



















declaration = "Wenn fliegen über Fliegen:\n"
sayings = ['"fliegen"'] * 3 + ['"nach"']

sentence = declaration + ", ".join(sayings) + "!"
print(sentence)
print()    # empty 'print' makes a newline

Wenn fliegen über Fliegen:
"fliegen", "fliegen", "fliegen", "nach"!



#### Escape-Sequenzen

In [5]:
print('Hello World (\') !')

Hello World (') !


In [6]:
print("Hello\tthere\nHow are you?") # 'tab' und 'new line'

Hello	there
How are you?


### String Formattierung
Es gibt eine Reihe von Möglichkeiten, Zeichenketten zu formattieren:

- C-style:
```python
"%s is: %.3f (or %d in Indiana)" % \
        ("Pi", math.pi, math.pi)
# %s = string
# %0.3f = floating point number, 3 places to the left of the decimal
# %d = decimal number
#
# Style notes:
#     Line continuation with '\' works but
#     is frowned upon. Indent twice
#     (8 spaces) so it doesn't look
#     like a control statement
```

In [7]:
import math
print("%s is: %.3f (well, %d on Mars)" % ("Pi", math.pi, math.pi))

Pi is: 3.142 (well, 3 on Mars)


In [8]:
# Anzahl der Dezimalstellen die gezeigt werden sollen, können per '.' kontrolliert werden
print("{0} is: {1} ({1:.3} truncated)".format("Pi", math.pi))

Pi is: 3.141592653589793 (3.14 truncated)


In [9]:
# Go to town -- change the decimal places!
print("{pi} is: {pie:05.2}".format(pi="Pi", pie=math.pi))

Pi is: 003.1


### Boolean (Wahrheitswerte)

In [34]:
type(True)

bool

In [35]:
type(False)

bool

### Complex Numbers (Komplexe Zahlen)

In [36]:
2+3j

(2+3j)

In [37]:
type(2+3j)

complex

## Arithmetische Ausdrücke

In [40]:
12783 + 1983 # Addition

14766

In [39]:
12783 - 1983 # Subtraktion

10800

In [41]:
12783 * 1983 # Multiplikation

25348689

In [42]:
12783 / 1983 # Division

6.446293494704992

In [43]:
12783 % 1983 # Rest bei Division

885

In [45]:
3 ** 2 # Exponent

9

## Kontrollstrukturen

### Gängige Vergleichs Operatoren

<table style="border:3px solid white;"><tr>
<td><tt>==</tt></td>
<td><tt>!=</tt></td>
<td><tt>&lt;=</tt> or <tt>&lt;</tt><br/>
    <tt>&gt;=</tt> or <tt>&gt;</tt></td>
<td><tt>x in (1, 2)</tt></td>
<td><tt>x is None<br/>
        x is not None</tt></td>
</tr><tr style="font-size:smaller;">
<td>equals</td>
<td>not equals</td>
<td>less or<br/>equal, etc.</td>
<td>works for sets,<br/>
           lists, tuples,<br/>
           dictionary keys,<br/>
           strings</td>
<td>just for <tt>None</tt></td>
</tr></table>

### If

In [10]:
note = 3.4
if note > 2.0:
    print ("Your application is accepted.")

Your application is accepted.


### Else

In [51]:
gpa = 1.4
if gpa > 2.0:
    print ("Welcome to Mars University!")
else:
    print ("Your application is denied.")


Your application is denied.


### Elif

In [53]:
gpa = 2.1
if gpa > 1.0:
    print ("Please take the entry test")
elif gpa > 3.0:
    print ("Welcome to Mars University!")
else:
    print ("Your application is denied.")


Please take the entry test


### Pass

In [58]:
a = 3
if a < 5:
    pass  # ignores the if-else part
else:
    print("a is greater or equal to 5")
print ("End of Program")

End of Program


### Challenge: If/Else

Schreibe ein Programm, das die Wurzel aus einer Zahl zieht.
Angenommen, die folgende Eingabe wird an das Programm übergeben:

4

Dann sollte die Ausgabe sein:

2

Sofern die geprüfte Zahl "" ist, soll "Bitte Zahl eingeben" zurückgegeben werden

Hinweis: Verwende die math.sqrt() Funktion zur berechnung der Wurzel.

### Lösung

In [54]:


















x = 4

if x == "":
    y = "Bitte Zahl eingeben"
else:
    y = math.sqrt(x)

print(y)

2.0


## Schleifen

### While Schleife

In [59]:
i = 0
while i < 3:
    print("i is:", i)
    i += 1

print("We exited the loop, and now i is:", i)

i is: 0
i is: 1
i is: 2
We exited the loop, and now i is: 3


### For Schleife

In [60]:
for i in range(3):
    print("in the for loop. `i` is:", i)

print()
print("outside the for loop. `i` is:", i)

in the for loop. `i` is: 0
in the for loop. `i` is: 1
in the for loop. `i` is: 2

outside the for loop. `i` is: 2


In [61]:
# or loop directly over a list or tuple
for element in ("one", 2, "three"):
    print("in the for loop. `element` is:", element)

print()
print("outside the for loop. `element` is:", element)

in the for loop. `element` is: one
in the for loop. `element` is: 2
in the for loop. `element` is: three

outside the for loop. `element` is: three


### Challenge: Schleifen I
Bitte schauen Sie sich diesen Code an und überlegen Sie, was passieren wird, kopieren Sie ihn dann und führen Sie ihn aus. Wir stellen `break` und` continue` vor ... kannst du erzählen was die machen?

- Wann wird es aufhören?
- Was wird gedruckt?
- Was wird "i" am Ende sein?

```python
for i in range(20):
    if i == 15:
        break
    elif i % 2 == 0:
        continue
    for j in range(5):
        print(i + j, end="...")
    print()  # newline
```

### Solution:

In [66]:













for i in range(20):
    if i == 15:
        break
    elif i % 2 == 0:
        continue
    for j in range(5):
        print(i + j, end="...")
    print()  # newline

1...2...3...4...5...
3...4...5...6...7...
5...6...7...8...9...
7...8...9...10...11...
9...10...11...12...13...
11...12...13...14...15...
13...14...15...16...17...


### Challenge: Schleifen II
Schreibe ein Programm, das alle Zahlen findet, die durch 7 teilbar sind, aber kein Vielfaches von 5 sind, zwischen 2000 und 3200 (beide enthalten).
Die erhaltenen Zahlen sollten in einer durch Kommas getrennten Reihenfolge in einer einzigen Zeile gedruckt werden.

### Solution:

In [40]:


















l=[]
for i in range(2000, 3201):
    if (i%7==0) and (i%5!=0):
        l.append(str(i))

print (', '.join(l))

2002, 2009, 2016, 2023, 2037, 2044, 2051, 2058, 2072, 2079, 2086, 2093, 2107, 2114, 2121, 2128, 2142, 2149, 2156, 2163, 2177, 2184, 2191, 2198, 2212, 2219, 2226, 2233, 2247, 2254, 2261, 2268, 2282, 2289, 2296, 2303, 2317, 2324, 2331, 2338, 2352, 2359, 2366, 2373, 2387, 2394, 2401, 2408, 2422, 2429, 2436, 2443, 2457, 2464, 2471, 2478, 2492, 2499, 2506, 2513, 2527, 2534, 2541, 2548, 2562, 2569, 2576, 2583, 2597, 2604, 2611, 2618, 2632, 2639, 2646, 2653, 2667, 2674, 2681, 2688, 2702, 2709, 2716, 2723, 2737, 2744, 2751, 2758, 2772, 2779, 2786, 2793, 2807, 2814, 2821, 2828, 2842, 2849, 2856, 2863, 2877, 2884, 2891, 2898, 2912, 2919, 2926, 2933, 2947, 2954, 2961, 2968, 2982, 2989, 2996, 3003, 3017, 3024, 3031, 3038, 3052, 3059, 3066, 3073, 3087, 3094, 3101, 3108, 3122, 3129, 3136, 3143, 3157, 3164, 3171, 3178, 3192, 3199


## Komplexe Datentypen

### List

In [24]:
l = ["a", 0, [1, 2] ]
l[1] = "second element"

type(l)

list

In [25]:
print(l)

['a', 'second element', [1, 2]]


In [26]:
indices = range(len(l))
print(indices)

range(0, 3)


In [27]:
# Iterieren Sie über die Indizes mit i=0, i=1, i=2
for i in indices:
    print(l[i])

a
second element
[1, 2]


In [28]:
# Oder iteriere direkt über die Elemente in `x`
for x in l:
    print(x)

a
second element
[1, 2]


#### Kopieren von Listen
Beim kopieren von Listen werden einzelne Attribute Kopiert. Selbes gilt für Sets, Dictionaries.

**Beispiel:**
```python
fifth_element = x[4]
fifth_element.append("Both!")
print(fifth_element)
print(x)
```
Der Zuweisungsoperator (`=`) kopiert den Zeiger an die Stelle, an der sich die Liste (oder das Dictionary oder Set) befindet: Es kopiert nicht den tatsächlichen Inhalt des gesamten Objekts, sondern nur die Adresse, an der sich die Daten befinden. Dies ist effizient, da das Objekt bspw. mehrere Megabyte groß sein könnte.

In [29]:
fifth_element = l[2]
print(fifth_element)

fifth_element.append("Both!")
print(fifth_element)

print(x)

[1, 2]
[1, 2, 'Both!']
[1, 2, 'Both!']


#### Duplizierte Kopie
[Das copy Modul ] [copy]

Beispiel:

```python
import copy

# -------------------- A shallow copy
x[4] = ["list"]
shallow_copy_of_x = copy.copy(x)
shallow_copy_of_x[0] = "Shallow copy"
fifth_element = x[4]
fifth_element.append("Both?")

def print_list(l):
   print("-" * 10)
   for elem in l:
       print(elem)
   print()

print_list(shallow_copy_of_x)
print_list(x)
fifth_element
```

[copy]: https://docs.python.org/3/library/copy.html

In [31]:
import copy

# -------------------- Flache Kopie
l[2] = ["list"]
shallow_copy_of_x = copy.copy(x)
shallow_copy_of_x[0] = "Shallow copy"
fifth_element = l[2]
fifth_element.append("Both?")

In [33]:
# look at them
def print_list(l):
   print("-" * 8, "die Liste, element-by-element", "-" * 8)
   for elem in l:
       print(elem)
   print()

print_list(shallow_copy_of_x)
print_list(x)

-------- die Liste, element-by-element --------
Shallow copy
2
Both!

-------- die Liste, element-by-element --------
1
2
Both!



#### Tiefe Kopie

```python
# -------------------- Tiefe Kopie

x[4] = ["list"]
deep_copy_of_x = copy.deepcopy(x)
deep_copy_of_x[0] = "Deep copy"
fifth_element = deep_copy_of_x[4]
fifth_element.append("Both?")

print_list(deep_copy_of_x)
print_list(x)
fifth_element
```

In [36]:
# -------------------- Tiefe Kopie

x[2] = ["list"]
deep_copy_of_x = copy.deepcopy(x)
deep_copy_of_x[0] = "Deep copy"
first_element = deep_copy_of_x[2]
first_element.append("Both? -- no, just this one got it!")

print(first_element)
print(x[2])

['list', 'Both? -- no, just this one got it!']
['list']


### Atomare Typen

<table style="border:3px solid white;"><tr>
<td> boolean</td>
<td> integer </td>
<td> float </td>
<td>string</td>
<td>None</td>
</tr><tr>
<td><tt>True</tt></td>
<td><tt>42</tt></td>
<td><tt>42.0</tt></td>
<td><tt>"hello"</tt></td>
<td><tt>None</tt></td>
</tr></table>

### Container Typen

<table style="border:3px solid white;"><tr>
<td> list </td>
<td> tuple </td>
<td> set </td>
<td>dictionary</td>
</tr><tr style="font-size:smaller;">
<td><ul style="margin:5px 2px 0px 15px;"><li>Iterable</li><li>Mutable</li>
       <li>No restriction on elements</li>
       <li>Elements are ordered</li></ul></td>
<td><ul style="margin:5px 2px 0px 15px;"><li>Iterable</li><li>Immutable</li>
       <li>Elements must be hashable</li>
       <li>Elements are ordered</li></ul></td>
<td><ul style="margin:5px 2px 0px 15px;"><li>Iterable</li><li>Mutable</li>
    <li>Elements are<br/>
    unique and must<br/>
    be hashable</li>
       <li>Elements are not ordered</li></ul></td>
<td><ul style="margin:5px 2px 0px 15px;"><li>Iterable</li><li>Mutable</li>
      <li>Key, value pairs.<br/>
      Keys are unique and<br/>
      must be hashable</li>
       <li>Keys are not ordered</li></ul></td>
</tr></table>

#### Iterable
Man kann eine Schleife darüber ziehen.

#### Mutable
Du kannst es verändern.

#### Hashable
Eine Hash-Funktion konvertiert ein Objekt in eine Zahl, die für das Objekt immer gleich ist. Sie helfen beim Identifizieren des Objekts.

### Tuple

In [73]:
t = ("a", 0, "tuple")
type(t)

tuple

In [74]:
for x in t:
    print(x)

a
0
tuple


### Set
Um eine Menge zu bilden, verwende die Funktion `set()`.
- Gegenstände in einem Set sind einzigartig
- Lists, Dictionaries und Tuple können nicht in einem Set enthalten sein

In [75]:
s = set(['a', 0])
if 'b' in s:
    print("has b")

In [76]:
s.add("b")
s.remove("a")

if 'b' in s:
    print("has b")

has b


In [79]:
l = [1,2,3]
try:
    s.add(l)
except TypeError:
    print("Could not add the list")
    #raise  # uncomment this to raise an error

Could not add the list


### Dictionary

In [82]:
#   zwei Möglichkeiten, das Selbe zu tun
d = {"mother":"hamster",
     "father":"elderberries"}
d = dict(mother="hamster",
         father="elderberries")

In [83]:
d['mother']

'hamster'

In [86]:
print("the dictionary keys:", d.keys())
print()
print("the dictionary values:", d.values())

the dictionary keys: dict_keys(['mother', 'father'])

the dictionary values: dict_values(['hamster', 'elderberries'])


In [91]:
# Iteriere über ein Dictionary, verwende 2 Iteratoren
for k, v in d.items():
    print("key: ", k, end="  ... ")
    print("val: ", v)

key:  mother  ... val:  hamster
key:  father  ... val:  elderberries


In [90]:
# ...ansonsten ist der Output die "keys"
for k in d:
    print(k)

mother
father


### Takeaways

```python
# Für weitere Informationen verwende, help(object)
help(tuple)
help(set)
help()
```

## Funktionen

Die Syntax zum Erstellen einer Funktion lautet:

```python
def function_name(arg1, arg2, kwarg1=default1):
    """Docstring goes here -- triple quoted."""
    pass  # the 'pass' keyword means 'do nothing'
    

# Die nächste nicht eingerückte Aussage ist außerhalb 
# der Funktion. Anweisungen werden durch ein Leerzeilegetrennt
```

- Das Schlüsselwort ** def ** eröffnet die Funktionsdeklaration.
- Der Doppelpunkt (`:`) beendet die Funktionsdeklaration.
- Der Körper muss eingerückt sein. Die Einrückung muss auf der gleichen Ebene sein.
- Es gibt keine geschweiften Klammern für Funktionskörper in Python - Leerraum am Anfang einer Zeile sagt Python, dass diese Zeile "innerhalb" des Körpers von dem ist, was davor kam.

In [92]:
def function_name(arg1, arg2, kwarg1="my_default_value"):
    """Docstring goes here -- triple quoted."""
    pass  # the 'pass' keyword means 'do nothing'

In [93]:
help(function_name)

Help on function function_name in module __main__:

function_name(arg1, arg2, kwarg1='my_default_value')
    Docstring goes here -- triple quoted.



### Whitespace
Das 'Tab'-Zeichen **' \ t '** zählt als ein einzelnes Zeichen, auch wenn es in Ihrem Editor wie mehrere Zeichen aussieht.

** Aber Einrückung ist, wie Verschachtelung zu bezeichnen! **

Einrückung kann ein Programm ernsthaft durcheinander bringen. Der [Python-Style-Guide] [pep8] empfiehlt, den Editor so zu konfigurieren, dass die Tab-Taste automatisch vier Leerzeichen ergibt.

[pep8]: https://www.python.org/dev/peps/pep-0008/

### Meiner erste Funktion
```python
def greet_person(person):
    """Greet the named person.

    usage:
        >>> greet_person("world")
        hello world
    """
    print('hello', person)
```

In [96]:
def greet_person(person):
    """Greet the named person.

    usage:
        >>> greet_person("world")
        hello world
    """
    print('hello', person)

In [97]:
# Hier ist die Hilfestellung
help(greet_person)

Help on function greet_person in module __main__:

greet_person(person)
    Greet the named person.
    
    usage:
        >>> greet_person("world")
        hello world



In [98]:
greet_person("world")

hello world


###  Challenge: Funktionen
Erstelle eine andere Funktion mit dem Namen `greet_people`, die eine Liste von Personen aufnimmt und sie alle nacheinander begrüßt. Tipp: Du kannst die Funktion `greet_person` aufrufen.

In [99]:
# Deine function
def greet_people(list_of_people)
    """Documentation string goes here."""
    # You do it here!
    pass

SyntaxError: invalid syntax (<ipython-input-99-d8822535ad13>, line 2)

###  Lösung

In [104]:


















def greet_people(list_of_people):
    for person in list_of_people:
        greet_person(person)

In [105]:
greet_people(["world", "awesome python user!", "rockstar!!!"])

hello world
hello awesome python user!
hello rockstar!!!


## Module

### math

In [106]:
import math

print("The square root of 3 is:", math.sqrt(3))
print("pi is:", math.pi)
print("The sin of  90 degrees is:", math.sin(math.radians(90)))

The square root of 3 is: 1.7320508075688772
pi is: 3.141592653589793
The sin of  90 degrees is: 1.0


- Die Anweisung `import` importiert das Modul in den Namespace
- Zugreifen auf Funktionen:
```python
      <module>.<function>
```      
- Du kannst über ein Module die Dokumentation aufrufen:
```python
    help(<module>)
```

### Challenge: math
Hinweis: `help (math)` zeigt alle Funktionen ...

- What is the arc cosine of `0.743144` in degrees?

### Lösung

In [108]:





























from math import acos, degrees  # use 'from' sparingly

int(degrees(acos(0.743144)))  # 'int' to make an integer

42

## Arrays

### Eindimensionale Arrays

In [1]:
# Install numpy in the current Jupyter kernel
import sys
!conda install --yes --prefix {sys.prefix} numpy

Solving environment: done

## Package Plan ##

  environment location: /home/ubuntu/miniconda3

  added / updated specs: 
    - numpy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    mkl_random-1.0.1           |   py37h4414c95_1         372 KB
    libgfortran-ng-7.3.0       |       hdf63c60_0         1.3 MB
    blas-1.0                   |              mkl           6 KB
    mkl-2019.0                 |              118       204.4 MB
    numpy-1.15.2               |   py37h1d66e8a_1          48 KB
    ------------------------------------------------------------
                                           Total:       206.1 MB

The following NEW packages will be INSTALLED:

    blas:           1.0-mkl              
    intel-openmp:   2019.0-118           
    libgfortran-ng: 7.3.0-hdf63c60_0     
    mkl:            2019.0-118           
    mkl_fft:        1.0.6-py37h7dd41cf_0 
    mkl

In [2]:
import numpy as np

print(np.array([1.0, 2, 3]))

[1. 2. 3.]


In [3]:
print(np.ones(5))

[1. 1. 1. 1. 1.]


In [4]:
print(np.arange(2.2, 3, 0.2, dtype=float))

[2.2 2.4 2.6 2.8]


### Mehrdimensionale Arrays

In [6]:
print(np.array([[1, 2, 3], [4, 5, 6]]))

[[1 2 3]
 [4 5 6]]


In [7]:
print(np.array([[[1,2,3], [4,5,6]], [[7,8,9], [0,1,2]]]))

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [0 1 2]]]


In [8]:
print(np.zeros((2, 2)))

[[0. 0.]
 [0. 0.]]


### Subarrays

In [11]:
a = np.array([[1,2,3,4,5,6], [7,8,9,0,1,2]])
print(a.shape)

(2, 6)


In [12]:
print(a[0,1::2])  

[2 4 6]


In [13]:
print(a[1:,1:])  

[[8 9 0 1 2]]


In [14]:
print(a[0, np.array([1,2,5])]) 

[2 3 6]


### Matrixoperationen

In [37]:
a = np.array([[1,2], [3,4]])
a = np.concatenate((a, [[5,6]]), axis=0)
print(a.transpose())
print("########################")
print(a.shape, a.transpose().shape)
print("########################")
print(a[1].reshape((2,1)))

[[1 3 5]
 [2 4 6]]
########################
(3, 2) (2, 3)
########################
[[3]
 [4]]


# You are done, welcome to Python!

# END